// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using uit_project_framework.Models;

namespace uit_project_framework.Migrations
{
    [DbContext(typeof(ShopContext))]
    [Migration("20200525135754_asdfasdfasdf")]
    partial class asdfasdfasdf
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("uit_project_framework.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Image")
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime?>("UpdatedAt");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new { CategoryId = 1, CategoryName = "the loai 1", Description = "mo ta 1", Image = "https://cdn.pixabay.com/photo/2016/11/09/16/24/virus-1812092__340.jpg" },
                        new { CategoryId = 2, CategoryName = "the loai 2", Description = "mo ta 2", Image = "https://cdn.pixabay.com/photo/2016/11/15/07/09/photo-manipulation-1825450__340.jpg" },
                        new { CategoryId = 3, CategoryName = "the loai 3", Description = "mo ta 3", Image = "https://cdn.pixabay.com/photo/2015/10/21/16/44/cold-999972__340.jpg" }
                    );
                });

            modelBuilder.Entity("uit_project_framework.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<decimal>("DiscountMoney");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Fullname")
                        .HasColumnType("varchar(250)");

                    b.Property<decimal>("OriginalMoney");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(250)");

                    b.Property<int>("ProductAmount");

                    b.Property<long>("ProductId");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("TotalMoney");

                    b.Property<DateTime?>("UpdatedAt");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("uit_project_framework.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<string>("Image")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdatedAt");

                    b.HasKey("PostId");

                    b.ToTable("Posts");

                    b.HasData(
                        new { PostId = 1, Content = "The key value is required so it must be supplied. When a migration is created, the SQL Server provider will enable the insertion of Identity values:", Image = "https://cdn.pixabay.com/photo/2016/11/09/16/24/virus-1812092__340.jpg", Title = "BAI VIET 1" },
                        new { PostId = 2, Content = "This site can’t be reached", Image = "https://cdn.pixabay.com/photo/2016/11/15/07/09/photo-manipulation-1825450__340.jpg", Title = "BAI VIET 2" },
                        new { PostId = 3, Content = "This site can’t be reached", Image = "https://cdn.pixabay.com/photo/2016/11/15/07/09/photo-manipulation-1825450__340.jpg", Title = "BAI VIET 3" },
                        new { PostId = 4, Content = "This site can’t be reached", Image = "https://cdn.pixabay.com/photo/2016/11/15/07/09/photo-manipulation-1825450__340.jpg", Title = "BAI VIET 4" }
                    );
                });

            modelBuilder.Entity("uit_project_framework.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CategoryID");

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<string>("Image")
                        .HasColumnType("varchar(250)");

                    b.Property<decimal?>("Price")
                        .IsRequired();

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime?>("UpdatedAt");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new { ProductId = 1, CategoryID = 1L, CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Image = "https://cdn.pixabay.com/photo/2016/11/09/16/24/virus-1812092__340.jpg", Price = 2223m, ProductName = "san pham 1", Unit = "cai", UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { ProductId = 2, CategoryID = 1L, CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Image = "https://cdn.pixabay.com/photo/2015/10/21/16/44/cold-999972__340.jpg", Price = 2223m, ProductName = "san pham 2", Unit = "cai", UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { ProductId = 3, CategoryID = 1L, CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Image = "https://cdn.pixabay.com/photo/2016/11/09/16/24/virus-1812092__340.jpg", Price = 666m, ProductName = "san pham 3", Unit = "mieng", UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified) },
                        new { ProductId = 4, CategoryID = 1L, CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Image = "https://cdn.pixabay.com/photo/2015/10/21/16/44/cold-999972__340.jpg", Price = 111m, ProductName = "san pham 4", Unit = "cuc", UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified) }
                    );
                });

            modelBuilder.Entity("uit_project_framework.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Role")
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime?>("UpdatedAt");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("uit_project_framework.Models.Voucher", b =>
                {
                    b.Property<int>("VoucherId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<decimal?>("Money")
                        .IsRequired();

                    b.Property<string>("Status")
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<string>("VoucherCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("VoucherId");

                    b.ToTable("Vouchers");
                });
#pragma warning restore 612, 618
        }
    }
}
